### PR TITLE
Spell checker strikes again

### PR DESCRIPTION
**Pull request by wobbol**
in all probablity the spell checker used garbled this.

### CODE REVIEW

**Comment by fabriziotappero** [comment]
Hi Wobbol. Can you please point out what the spelling mistake is? I can't spot it.
cheers

**Comment by wobbol** [comment]
Sorry for the bad commit message.

I replaced not with nor in the second sentence because

Both (condition) and (condition);
Nether (condition) nor (condition)

Converted to logic symbols

P && Q ;
!P || !Q

Mirrors DeMorgan's laws.

Also my English teacher would fuss at me .

**Comment by fabriziotappero** [comment]
in this particular commitment I do not see any text change. Plus what you explain last does not seem a spelling mistake. Please clarify.

**Comment by wobbol** [comment]
Sorry, it's early here and I was on my smartphone.

This is the sentence I was referring to
"However, one of the data types, similar to std_logic, neither used not endorsed in this book is the bit type."

When neither is used as a conjunction its supporting conjunction(I don't know the technical term for this off the top of my head) must be nor.
~~if not is used as a conjunction then neither can be used as a supporting conjunction though.~~

[Neither, neither … nor and not … either (source)](http://dictionary.cambridge.org/us/grammar/british-grammar/neither-neither-nor-and-not-either)
EDIT:I was wrong about the last statement

**Comment by fabriziotappero** [comment]
ah, I see, you are totally right. Just accepted it. So back to the 
P && Q ;
!P || !Q

Does this refer to a pull request you submitted? it doesn't, does it?

thanks for your time.

**Comment by fabriziotappero** [comment]
hahaha, I now understand what you meant by that! sorry mate you just chose a Boolean explanation of some English thing... hahaah I did not get it. Alright then, if you have any more suggestions I am here.
cheers
f.

**Comment by wobbol** [comment]
I'll try to be more verbose in the future. Should grammar correction commit
messages contain a reputable source and an explanation?

**Comment by fabriziotappero** [comment]
Your commits are great as they are. 
Cheers

**Pull request merged**
